# -*- coding: utf-8 -*-
"""Pipeline_NLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eAnGYaVCJht-BX7btjo2wran0ZLaXq07
"""

!pip install -q transformers

from transformers import pipeline

classifier = pipeline("sentiment-analysis")

text="It's great to learn NLP for me"

classifier(text)

import pandas as pd

outputs=classifier(text)
pd.DataFrame(outputs)

classifier=pipeline("zero-shot-classification")
text="this is a tutorial about Hugging Face"

labels=["tech","education","business"]

outputs=classifier(text,labels)
pd.DataFrame(outputs)

generator=pipeline("text-generation")

prompt="This tutorial will walk you through how to"

generator(prompt)

outputs=generator(prompt,max_length=50)
print(outputs[0]["generated_text"])

generator=pipeline("text-generation",model="distilgpt2")

outputs=generator(prompt,max_length=50)
print(outputs[0]["generated_text"])

ner=pipeline("ner",grouped_entities=True)

text="My name is Mert from Turkey. HuggingFace is a nice program"

outputs=ner(text)
pd.DataFrame(outputs)

reader=pipeline("question-answering")

text="My name is Mert and I love Berlin"
question="Where do I like"

outputs=reader(question=question,context=text)
pd.DataFrame([outputs])

summarizer=pipeline("summarization")

text="Three men came to New York for a holiday. They came to a very large hotel and took a room there. Their room was on the forty-fifth floor. In the evening friends went to the theatre and came back to the hotel very late. “I’m very sorry,” said the clerk of the hotel, “but the lifts don’t work tonight. If you don’t want to walk up to your room, we shall make beds for you in the hall.” “No, no,” said one of the friends, “no, thank you. We don’t want to sleep in the hall. We shall walk up to our room.” Then he turned to his friends and said: “It’s not easy to walk up to the forty-fifth floor, but we shall make it easier. On the way to the room I shall tell you some jokes; then you, Andy, will sing us some songs; then you, Peter, will tell us some interesting stories.” So they began walking up to their room. Tom told them many jokes; Andy sang some songs. At last, they came to the thirty-sixth floor. They were tired and decided to have a rest. “Well,” said Tom, “now it’s your turn, Peter. After all the jokes, I would like to hear a sad story. Tell us a long and interesting story with a sad end.” “The story which I’m going to tell you,” said Peter, “is sad enough. We left the key to our room in the hall.”"

output=summarizer(text,clean_up_tokenization_spaces=True)

print(output[0]["summary_text"])

translator=pipeline("translation_en_to_de")

text="I hope you enjoy it"

output=translator(text)
print(output[0]["translation_text"])