# -*- coding: utf-8 -*-
"""speech_reco_nlp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-gYdJv3ANZcQBaLobeFYhcUM1nIwpYNM
"""

!pip install -q transformers

from transformers import pipeline
speech_recognizer = pipeline("automatic-speech-recognition")

!pip install -q datasets

from datasets import load_dataset
dataset = load_dataset("PolyAI/minds14",name="en-US",split="train")

dataset.features

from datasets import Audio
dataset = dataset.cast_column("audio",Audio(sampling_rate=speech_recognizer.feature_extractor.sampling_rate))

data=dataset[:4]["audio"]
result=speech_recognizer(data)

print([d["text"] for  d in result])

model_name="nlptown/bert-base-multilingual-uncased-sentiment"

from transformers import AutoModelForSequenceClassification
model=AutoModelForSequenceClassification.from_pretrained(model_name)

from transformers import AutoTokenizer #tokenizer metinleri modelin anlayacağı şekilde çevirir
tokenizer=AutoTokenizer.from_pretrained(model_name)

classifier=pipeline("sentiment-analysis",model=model,tokenizer=tokenizer)

text="Ce film est magnifique, je l'ai beaucoup aimé"

classifier(text)

encoding=tokenizer("This film is nice, I liked")
print(encoding)

