# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CiUaHhAlHCcyzmMbOCdnrMGim57pwgvz
"""

!pip install -q -U transformers bitsandbytes peft datasets trl

from transformers import AutoTokenizer

base_model="mistralai/Mistral-7B-v0.1"

from transformers import AutoTokenizer

token = ""
base_model = "mistralai/Mistral-7B-v0.1"

tokenizer = AutoTokenizer.from_pretrained(
    base_model,
    add_eos_token=True,
    padding_side="right",
    use_auth_token=token
)

tokenizer.pad_token = tokenizer.eos_token

tokenizer.add_bos_token,tokenizer.add_eos_token

from transformers import BitsAndBytesConfig

import torch
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=False,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)

from transformers import AutoModelForCausalLM

model = AutoModelForCausalLM.from_pretrained(
    base_model,
    quantization_config=bnb_config,
    torch_dtype=torch.bfloat16,
    device_map="auto",
    use_auth_token=token

)

from datasets import load_dataset

dataset_name = "databricks/databricks-dolly-15k"

train_dataset = load_dataset(dataset_name, split="train[0:800]")
eval_dataset = load_dataset(dataset_name, split="train[800:1000]")

train_dataset

train_dataset.to_pandas()

train_dataset.to_pandas().dtypes

train_dataset.to_pandas().dtypes

def generate_prompt(sample):
    full_prompt =f"""<s>[INST]{sample['instruction']}
    {f"Here is some context: {sample['context']}" if len(sample["context"]) > 0 else None}
    [/INST] {sample['response']}</s>"""
    return {"text": full_prompt}

train_dataset[0]

generated_train_dataset = train_dataset.map(
    generate_prompt, remove_columns=list(train_dataset.features))
generated_val_dataset = eval_dataset.map(
    generate_prompt, remove_columns=list(train_dataset.features))

from peft import prepare_model_for_kbit_training

model.gradient_checkpointing_enable()

model = prepare_model_for_kbit_training(model)

def print_trainable_parameters(model):
    trainable_params = 0
    all_param = 0
    for _, param in model.named_parameters():
        all_param += param.numel()
        if param.requires_grad:
            trainable_params += param.numel()
    print(
        f"trainable params: {trainable_params} || all params: {all_param} || trainable%: {100 * trainable_params / all_param}"
    )

from peft import LoraConfig, get_peft_model

lora_config = LoraConfig(
    r=8, #rank sayısı arttıkça eğitilecek parametre sayısı artar 8-120 arası seçilir
    lora_alpha=16, #öğrenilecek ağırlıklar için ölçekleme parametresi
    #genelde en uygunu r 64 alpha 16 olarak gösterilir
    target_modules=[
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj",
        "gate_proj",
        "up_proj",
        "down_proj",
        "lm_head",
    ],
    bias="none",
    lora_dropout=0.05,
    task_type="CAUSAL_LM",
)

from peft import get_peft_model

model = get_peft_model(model, lora_config)

print_trainable_parameters(model)

print(model)

from huggingface_hub import notebook_login

notebook_login()

from transformers import TrainingArguments

training_arguments = TrainingArguments(
    output_dir="./results",
    num_train_epochs=1,
    per_device_train_batch_size=4,
    gradient_accumulation_steps=1,
    optim="paged_adamw_32bit",
    save_strategy="steps",
    save_steps=25,
    logging_steps=25,
    learning_rate=2e-4,
    weight_decay=0.001,
    max_steps=50,
    evaluation_strategy="steps",
    eval_steps=25,
    do_eval=True,
    report_to="none",
)

from trl import SFTTrainer

# Setting sft parameters
trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    args=training_arguments,
    train_dataset=generated_train_dataset,
    eval_dataset=generated_val_dataset,
    peft_config=lora_config,
)

model.config.use_cache = False #eğitim aşamasındayız diye
trainer.train()

my_finetuned_model = "Mistral-7b-Dolly"

trainer.model.push_to_hub(my_finetuned_model)

